export interface SP500Company {
  symbol: string
  name: string
  sector: string
  industry: string
}

export const SP500_LIST: SP500Company[] = [
  // ─── Information Technology ───
  { symbol: 'AAPL', name: 'Apple Inc.', sector: 'Information Technology', industry: 'Technology Hardware, Storage & Peripherals' },
  { symbol: 'MSFT', name: 'Microsoft Corporation', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation', sector: 'Information Technology', industry: 'Semiconductors' },
  { symbol: 'AVGO', name: 'Broadcom Inc.', sector: 'Information Technology', industry: 'Semiconductors' },
  { symbol: 'ORCL', name: 'Oracle Corporation', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'CRM', name: 'Salesforce Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'ADBE', name: 'Adobe Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.', sector: 'Information Technology', industry: 'Communications Equipment' },
  { symbol: 'ACN', name: 'Accenture plc', sector: 'Information Technology', industry: 'IT Services' },
  { symbol: 'INTC', name: 'Intel Corporation', sector: 'Information Technology', industry: 'Semiconductors' },
  { symbol: 'AMD', name: 'Advanced Micro Devices Inc.', sector: 'Information Technology', industry: 'Semiconductors' },
  { symbol: 'IBM', name: 'International Business Machines Corp.', sector: 'Information Technology', industry: 'IT Services' },
  { symbol: 'QCOM', name: 'QUALCOMM Incorporated', sector: 'Information Technology', industry: 'Semiconductors' },
  { symbol: 'TXN', name: 'Texas Instruments Incorporated', sector: 'Information Technology', industry: 'Semiconductors' },
  { symbol: 'MU', name: 'Micron Technology Inc.', sector: 'Information Technology', industry: 'Semiconductors' },
  { symbol: 'SAP', name: 'SAP SE', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'NOW', name: 'ServiceNow Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'UBER', name: 'Uber Technologies Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.', sector: 'Information Technology', industry: 'Semiconductor Equipment' },
  { symbol: 'LRCX', name: 'Lam Research Corporation', sector: 'Information Technology', industry: 'Semiconductor Equipment' },
  { symbol: 'KLAC', name: 'KLA Corporation', sector: 'Information Technology', industry: 'Semiconductor Equipment' },
  { symbol: 'ADI', name: 'Analog Devices Inc.', sector: 'Information Technology', industry: 'Semiconductors' },
  { symbol: 'FIS', name: 'Fidelity National Information Services', sector: 'Information Technology', industry: 'IT Services' },
  { symbol: 'FISV', name: 'Fiserv Inc.', sector: 'Information Technology', industry: 'IT Services' },
  { symbol: 'APH', name: 'Amphenol Corporation', sector: 'Information Technology', industry: 'Electronic Components' },
  { symbol: 'IT', name: 'Gartner Inc.', sector: 'Information Technology', industry: 'IT Services' },
  { symbol: 'ROP', name: 'Roper Technologies Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'SNPS', name: 'Synopsys Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'CDNS', name: 'Cadence Design Systems Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'ANSS', name: 'ANSYS Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'FTNT', name: 'Fortinet Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'MRVL', name: 'Marvell Technology Inc.', sector: 'Information Technology', industry: 'Semiconductors' },
  { symbol: 'MCHP', name: 'Microchip Technology Inc.', sector: 'Information Technology', industry: 'Semiconductors' },
  { symbol: 'NXPI', name: 'NXP Semiconductors N.V.', sector: 'Information Technology', industry: 'Semiconductors' },
  { symbol: 'WDAY', name: 'Workday Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'HPQ', name: 'HP Inc.', sector: 'Information Technology', industry: 'Technology Hardware' },
  { symbol: 'DELL', name: 'Dell Technologies Inc.', sector: 'Information Technology', industry: 'Technology Hardware' },
  { symbol: 'HPE', name: 'Hewlett Packard Enterprise Co.', sector: 'Information Technology', industry: 'Technology Hardware' },
  { symbol: 'STX', name: 'Seagate Technology Holdings plc', sector: 'Information Technology', industry: 'Technology Hardware' },
  { symbol: 'WDC', name: 'Western Digital Corporation', sector: 'Information Technology', industry: 'Technology Hardware' },
  { symbol: 'GLW', name: 'Corning Incorporated', sector: 'Information Technology', industry: 'Electronic Components' },
  { symbol: 'JBL', name: 'Jabil Inc.', sector: 'Information Technology', industry: 'Electronic Manufacturing' },
  { symbol: 'KEYS', name: 'Keysight Technologies Inc.', sector: 'Information Technology', industry: 'Electronic Equipment' },
  { symbol: 'TDY', name: 'Teledyne Technologies Inc.', sector: 'Information Technology', industry: 'Electronic Equipment' },
  { symbol: 'TER', name: 'Teradyne Inc.', sector: 'Information Technology', industry: 'Semiconductor Equipment' },
  { symbol: 'ENPH', name: 'Enphase Energy Inc.', sector: 'Information Technology', industry: 'Solar Technology' },
  { symbol: 'ZBRA', name: 'Zebra Technologies Corporation', sector: 'Information Technology', industry: 'Electronic Equipment' },
  { symbol: 'FFIV', name: 'F5 Inc.', sector: 'Information Technology', industry: 'Communications Equipment' },
  { symbol: 'AKAM', name: 'Akamai Technologies Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'VRSN', name: 'VeriSign Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'TRMB', name: 'Trimble Inc.', sector: 'Information Technology', industry: 'Software' },
  { symbol: 'SMCI', name: 'Super Micro Computer Inc.', sector: 'Information Technology', industry: 'Technology Hardware' },
  { symbol: 'MPWR', name: 'Monolithic Power Systems Inc.', sector: 'Information Technology', industry: 'Semiconductors' },

  // ─── Health Care ───
  { symbol: 'UNH', name: 'UnitedHealth Group Incorporated', sector: 'Health Care', industry: 'Managed Health Care' },
  { symbol: 'JNJ', name: 'Johnson & Johnson', sector: 'Health Care', industry: 'Pharmaceuticals' },
  { symbol: 'PFE', name: 'Pfizer Inc.', sector: 'Health Care', industry: 'Pharmaceuticals' },
  { symbol: 'ABBV', name: 'AbbVie Inc.', sector: 'Health Care', industry: 'Pharmaceuticals' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.', sector: 'Health Care', industry: 'Pharmaceuticals' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.', sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  { symbol: 'ABT', name: 'Abbott Laboratories', sector: 'Health Care', industry: 'Health Care Equipment' },
  { symbol: 'DHR', name: 'Danaher Corporation', sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb Company', sector: 'Health Care', industry: 'Pharmaceuticals' },
  { symbol: 'LLY', name: 'Eli Lilly and Company', sector: 'Health Care', industry: 'Pharmaceuticals' },
  { symbol: 'CVS', name: 'CVS Health Corporation', sector: 'Health Care', industry: 'Health Care Services' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.', sector: 'Health Care', industry: 'Health Care Equipment' },
  { symbol: 'SYK', name: 'Stryker Corporation', sector: 'Health Care', industry: 'Health Care Equipment' },
  { symbol: 'EW', name: 'Edwards Lifesciences Corporation', sector: 'Health Care', industry: 'Health Care Equipment' },
  { symbol: 'BSX', name: 'Boston Scientific Corporation', sector: 'Health Care', industry: 'Health Care Equipment' },
  { symbol: 'MDT', name: 'Medtronic plc', sector: 'Health Care', industry: 'Health Care Equipment' },
  { symbol: 'ZTS', name: 'Zoetis Inc.', sector: 'Health Care', industry: 'Pharmaceuticals' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc.', sector: 'Health Care', industry: 'Biotechnology' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Incorporated', sector: 'Health Care', industry: 'Biotechnology' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.', sector: 'Health Care', industry: 'Biotechnology' },
  { symbol: 'AMGN', name: 'Amgen Inc.', sector: 'Health Care', industry: 'Biotechnology' },
  { symbol: 'BIIB', name: 'Biogen Inc.', sector: 'Health Care', industry: 'Biotechnology' },
  { symbol: 'ILMN', name: 'Illumina Inc.', sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  { symbol: 'WAT', name: 'Waters Corporation', sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  { symbol: 'A', name: 'Agilent Technologies Inc.', sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  { symbol: 'IDXX', name: 'IDEXX Laboratories Inc.', sector: 'Health Care', industry: 'Health Care Equipment' },
  { symbol: 'HOLX', name: 'Hologic Inc.', sector: 'Health Care', industry: 'Health Care Equipment' },
  { symbol: 'DVA', name: 'DaVita Inc.', sector: 'Health Care', industry: 'Health Care Services' },
  { symbol: 'UHS', name: 'Universal Health Services Inc.', sector: 'Health Care', industry: 'Health Care Services' },
  { symbol: 'HCA', name: 'HCA Healthcare Inc.', sector: 'Health Care', industry: 'Health Care Facilities' },
  { symbol: 'INCY', name: 'Incyte Corporation', sector: 'Health Care', industry: 'Biotechnology' },
  { symbol: 'MRNA', name: 'Moderna Inc.', sector: 'Health Care', industry: 'Biotechnology' },
  { symbol: 'ALGN', name: 'Align Technology Inc.', sector: 'Health Care', industry: 'Health Care Equipment' },
  { symbol: 'STE', name: 'STERIS plc', sector: 'Health Care', industry: 'Health Care Equipment' },
  { symbol: 'COO', name: 'The Cooper Companies Inc.', sector: 'Health Care', industry: 'Health Care Equipment' },
  { symbol: 'BAX', name: 'Baxter International Inc.', sector: 'Health Care', industry: 'Health Care Equipment' },
  { symbol: 'BDX', name: 'Becton Dickinson and Company', sector: 'Health Care', industry: 'Health Care Equipment' },
  { symbol: 'PKI', name: 'Revvity Inc.', sector: 'Health Care', industry: 'Life Sciences Tools & Services' },
  { symbol: 'LH', name: 'Laboratory Corporation of America', sector: 'Health Care', industry: 'Health Care Services' },
  { symbol: 'DGX', name: 'Quest Diagnostics Incorporated', sector: 'Health Care', industry: 'Health Care Services' },

  // ─── Financials ───
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'BAC', name: 'Bank of America Corporation', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'WFC', name: 'Wells Fargo & Company', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'C', name: 'Citigroup Inc.', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'GS', name: 'The Goldman Sachs Group Inc.', sector: 'Financials', industry: 'Investment Banking' },
  { symbol: 'MS', name: 'Morgan Stanley', sector: 'Financials', industry: 'Investment Banking' },
  { symbol: 'V', name: 'Visa Inc.', sector: 'Financials', industry: 'Transaction & Payment Processing' },
  { symbol: 'MA', name: 'Mastercard Incorporated', sector: 'Financials', industry: 'Transaction & Payment Processing' },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.', sector: 'Financials', industry: 'Transaction & Payment Processing' },
  { symbol: 'BLK', name: 'BlackRock Inc.', sector: 'Financials', industry: 'Asset Management' },
  { symbol: 'SCHW', name: 'The Charles Schwab Corporation', sector: 'Financials', industry: 'Investment Banking' },
  { symbol: 'AXP', name: 'American Express Company', sector: 'Financials', industry: 'Consumer Finance' },
  { symbol: 'SPGI', name: 'S&P Global Inc.', sector: 'Financials', industry: 'Financial Exchanges & Data' },
  { symbol: 'MCO', name: 'Moody\'s Corporation', sector: 'Financials', industry: 'Financial Exchanges & Data' },
  { symbol: 'MSCI', name: 'MSCI Inc.', sector: 'Financials', industry: 'Financial Exchanges & Data' },
  { symbol: 'CME', name: 'CME Group Inc.', sector: 'Financials', industry: 'Financial Exchanges & Data' },
  { symbol: 'ICE', name: 'Intercontinental Exchange Inc.', sector: 'Financials', industry: 'Financial Exchanges & Data' },
  { symbol: 'COF', name: 'Capital One Financial Corporation', sector: 'Financials', industry: 'Consumer Finance' },
  { symbol: 'USB', name: 'U.S. Bancorp', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'PNC', name: 'The PNC Financial Services Group', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'TFC', name: 'Truist Financial Corporation', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'BK', name: 'The Bank of New York Mellon Corporation', sector: 'Financials', industry: 'Asset Management' },
  { symbol: 'STT', name: 'State Street Corporation', sector: 'Financials', industry: 'Asset Management' },
  { symbol: 'AIG', name: 'American International Group Inc.', sector: 'Financials', industry: 'Multi-line Insurance' },
  { symbol: 'MET', name: 'MetLife Inc.', sector: 'Financials', industry: 'Life Insurance' },
  { symbol: 'PRU', name: 'Prudential Financial Inc.', sector: 'Financials', industry: 'Life Insurance' },
  { symbol: 'ALL', name: 'The Allstate Corporation', sector: 'Financials', industry: 'Property & Casualty Insurance' },
  { symbol: 'TRV', name: 'The Travelers Companies Inc.', sector: 'Financials', industry: 'Property & Casualty Insurance' },
  { symbol: 'CB', name: 'Chubb Limited', sector: 'Financials', industry: 'Property & Casualty Insurance' },
  { symbol: 'MMC', name: 'Marsh & McLennan Companies Inc.', sector: 'Financials', industry: 'Insurance Brokers' },
  { symbol: 'AON', name: 'Aon plc', sector: 'Financials', industry: 'Insurance Brokers' },
  { symbol: 'AJG', name: 'Arthur J. Gallagher & Co.', sector: 'Financials', industry: 'Insurance Brokers' },
  { symbol: 'FITB', name: 'Fifth Third Bancorp', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'SIVBQ', name: 'SVB Financial Group', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'ZION', name: 'Zions Bancorporation', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'CMA', name: 'Comerica Incorporated', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'KEY', name: 'KeyCorp', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'HBAN', name: 'Huntington Bancshares Incorporated', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'RF', name: 'Regions Financial Corporation', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'CFG', name: 'Citizens Financial Group Inc.', sector: 'Financials', industry: 'Diversified Banks' },
  { symbol: 'NDAQ', name: 'Nasdaq Inc.', sector: 'Financials', industry: 'Financial Exchanges & Data' },
  { symbol: 'CBOE', name: 'Cboe Global Markets Inc.', sector: 'Financials', industry: 'Financial Exchanges & Data' },
  { symbol: 'TROW', name: 'T. Rowe Price Group Inc.', sector: 'Financials', industry: 'Asset Management' },
  { symbol: 'IVZ', name: 'Invesco Ltd.', sector: 'Financials', industry: 'Asset Management' },

  // ─── Consumer Discretionary ───
  { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Consumer Discretionary', industry: 'Internet & Direct Marketing Retail' },
  { symbol: 'TSLA', name: 'Tesla Inc.', sector: 'Consumer Discretionary', industry: 'Automobiles' },
  { symbol: 'HD', name: 'The Home Depot Inc.', sector: 'Consumer Discretionary', industry: 'Home Improvement Retail' },
  { symbol: 'MCD', name: 'McDonald\'s Corporation', sector: 'Consumer Discretionary', industry: 'Restaurants' },
  { symbol: 'NKE', name: 'NIKE Inc.', sector: 'Consumer Discretionary', industry: 'Apparel & Footwear' },
  { symbol: 'SBUX', name: 'Starbucks Corporation', sector: 'Consumer Discretionary', industry: 'Restaurants' },
  { symbol: 'LOW', name: 'Lowe\'s Companies Inc.', sector: 'Consumer Discretionary', industry: 'Home Improvement Retail' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.', sector: 'Consumer Discretionary', industry: 'Internet & Direct Marketing Retail' },
  { symbol: 'ABNB', name: 'Airbnb Inc.', sector: 'Consumer Discretionary', industry: 'Internet & Direct Marketing Retail' },
  { symbol: 'CMG', name: 'Chipotle Mexican Grill Inc.', sector: 'Consumer Discretionary', industry: 'Restaurants' },
  { symbol: 'TJX', name: 'The TJX Companies Inc.', sector: 'Consumer Discretionary', industry: 'Apparel Retail' },
  { symbol: 'ROST', name: 'Ross Stores Inc.', sector: 'Consumer Discretionary', industry: 'Apparel Retail' },
  { symbol: 'TGT', name: 'Target Corporation', sector: 'Consumer Discretionary', industry: 'General Merchandise Stores' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Consumer Discretionary', industry: 'Internet & Direct Marketing Retail' },
  { symbol: 'GM', name: 'General Motors Company', sector: 'Consumer Discretionary', industry: 'Automobiles' },
  { symbol: 'F', name: 'Ford Motor Company', sector: 'Consumer Discretionary', industry: 'Automobiles' },
  { symbol: 'RIVN', name: 'Rivian Automotive Inc.', sector: 'Consumer Discretionary', industry: 'Automobiles' },
  { symbol: 'MAR', name: 'Marriott International Inc.', sector: 'Consumer Discretionary', industry: 'Hotels & Resorts' },
  { symbol: 'HLT', name: 'Hilton Worldwide Holdings Inc.', sector: 'Consumer Discretionary', industry: 'Hotels & Resorts' },
  { symbol: 'DRI', name: 'Darden Restaurants Inc.', sector: 'Consumer Discretionary', industry: 'Restaurants' },
  { symbol: 'YUM', name: 'Yum! Brands Inc.', sector: 'Consumer Discretionary', industry: 'Restaurants' },
  { symbol: 'DPZ', name: 'Domino\'s Pizza Inc.', sector: 'Consumer Discretionary', industry: 'Restaurants' },
  { symbol: 'EBAY', name: 'eBay Inc.', sector: 'Consumer Discretionary', industry: 'Internet & Direct Marketing Retail' },
  { symbol: 'ETSY', name: 'Etsy Inc.', sector: 'Consumer Discretionary', industry: 'Internet & Direct Marketing Retail' },
  { symbol: 'EXPE', name: 'Expedia Group Inc.', sector: 'Consumer Discretionary', industry: 'Internet & Direct Marketing Retail' },
  { symbol: 'NCLH', name: 'Norwegian Cruise Line Holdings', sector: 'Consumer Discretionary', industry: 'Hotels & Resorts' },
  { symbol: 'RCL', name: 'Royal Caribbean Cruises Ltd.', sector: 'Consumer Discretionary', industry: 'Hotels & Resorts' },
  { symbol: 'CCL', name: 'Carnival Corporation', sector: 'Consumer Discretionary', industry: 'Hotels & Resorts' },
  { symbol: 'WYNN', name: 'Wynn Resorts Limited', sector: 'Consumer Discretionary', industry: 'Casinos & Gaming' },
  { symbol: 'LVS', name: 'Las Vegas Sands Corp.', sector: 'Consumer Discretionary', industry: 'Casinos & Gaming' },
  { symbol: 'MGM', name: 'MGM Resorts International', sector: 'Consumer Discretionary', industry: 'Casinos & Gaming' },
  { symbol: 'HAS', name: 'Hasbro Inc.', sector: 'Consumer Discretionary', industry: 'Leisure Products' },
  { symbol: 'BBY', name: 'Best Buy Co. Inc.', sector: 'Consumer Discretionary', industry: 'Computer & Electronics Retail' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.', sector: 'Consumer Discretionary', industry: 'Internet & Direct Marketing Retail' },
  { symbol: 'TSLA', name: 'Tesla Inc.', sector: 'Consumer Discretionary', industry: 'Automobiles' },
  { symbol: 'VFC', name: 'V.F. Corporation', sector: 'Consumer Discretionary', industry: 'Apparel & Footwear' },
  { symbol: 'RL', name: 'Ralph Lauren Corporation', sector: 'Consumer Discretionary', industry: 'Apparel & Footwear' },
  { symbol: 'TPR', name: 'Tapestry Inc.', sector: 'Consumer Discretionary', industry: 'Apparel & Footwear' },
  { symbol: 'CPRI', name: 'Capri Holdings Limited', sector: 'Consumer Discretionary', industry: 'Apparel & Footwear' },
  { symbol: 'WHR', name: 'Whirlpool Corporation', sector: 'Consumer Discretionary', industry: 'Home Furnishings' },

  // ─── Communication Services ───
  { symbol: 'GOOGL', name: 'Alphabet Inc. (Class A)', sector: 'Communication Services', industry: 'Interactive Media & Services' },
  { symbol: 'GOOG', name: 'Alphabet Inc. (Class C)', sector: 'Communication Services', industry: 'Interactive Media & Services' },
  { symbol: 'META', name: 'Meta Platforms Inc.', sector: 'Communication Services', industry: 'Interactive Media & Services' },
  { symbol: 'NFLX', name: 'Netflix Inc.', sector: 'Communication Services', industry: 'Entertainment' },
  { symbol: 'DIS', name: 'The Walt Disney Company', sector: 'Communication Services', industry: 'Entertainment' },
  { symbol: 'CMCSA', name: 'Comcast Corporation', sector: 'Communication Services', industry: 'Cable & Satellite' },
  { symbol: 'VZ', name: 'Verizon Communications Inc.', sector: 'Communication Services', industry: 'Integrated Telecommunication Services' },
  { symbol: 'T', name: 'AT&T Inc.', sector: 'Communication Services', industry: 'Integrated Telecommunication Services' },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.', sector: 'Communication Services', industry: 'Wireless Telecommunication Services' },
  { symbol: 'WBD', name: 'Warner Bros. Discovery Inc.', sector: 'Communication Services', industry: 'Entertainment' },
  { symbol: 'PARA', name: 'Paramount Global', sector: 'Communication Services', industry: 'Movies & Entertainment' },
  { symbol: 'EA', name: 'Electronic Arts Inc.', sector: 'Communication Services', industry: 'Interactive Home Entertainment' },
  { symbol: 'TTWO', name: 'Take-Two Interactive Software Inc.', sector: 'Communication Services', industry: 'Interactive Home Entertainment' },
  { symbol: 'ROKU', name: 'Roku Inc.', sector: 'Communication Services', industry: 'Interactive Home Entertainment' },
  { symbol: 'SNAP', name: 'Snap Inc.', sector: 'Communication Services', industry: 'Interactive Media & Services' },
  { symbol: 'PINS', name: 'Pinterest Inc.', sector: 'Communication Services', industry: 'Interactive Media & Services' },
  { symbol: 'MTCH', name: 'Match Group Inc.', sector: 'Communication Services', industry: 'Interactive Media & Services' },
  { symbol: 'ZG', name: 'Zillow Group Inc.', sector: 'Communication Services', industry: 'Interactive Media & Services' },
  { symbol: 'OMC', name: 'Omnicom Group Inc.', sector: 'Communication Services', industry: 'Advertising' },
  { symbol: 'IPG', name: 'The Interpublic Group of Companies Inc.', sector: 'Communication Services', industry: 'Advertising' },
  { symbol: 'CHTR', name: 'Charter Communications Inc.', sector: 'Communication Services', industry: 'Cable & Satellite' },
  { symbol: 'TKO', name: 'TKO Group Holdings Inc.', sector: 'Communication Services', industry: 'Entertainment' },
  { symbol: 'LYV', name: 'Live Nation Entertainment Inc.', sector: 'Communication Services', industry: 'Entertainment' },

  // ─── Industrials ───
  { symbol: 'GE', name: 'General Electric Company', sector: 'Industrials', industry: 'Industrial Conglomerates' },
  { symbol: 'CAT', name: 'Caterpillar Inc.', sector: 'Industrials', industry: 'Construction Machinery' },
  { symbol: 'UNP', name: 'Union Pacific Corporation', sector: 'Industrials', industry: 'Railroads' },
  { symbol: 'UPS', name: 'United Parcel Service Inc.', sector: 'Industrials', industry: 'Air Freight & Logistics' },
  { symbol: 'BA', name: 'The Boeing Company', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { symbol: 'HON', name: 'Honeywell International Inc.', sector: 'Industrials', industry: 'Industrial Conglomerates' },
  { symbol: 'RTX', name: 'RTX Corporation', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { symbol: 'LMT', name: 'Lockheed Martin Corporation', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { symbol: 'GD', name: 'General Dynamics Corporation', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { symbol: 'NOC', name: 'Northrop Grumman Corporation', sector: 'Industrials', industry: 'Aerospace & Defense' },
  { symbol: 'MMM', name: '3M Company', sector: 'Industrials', industry: 'Industrial Conglomerates' },
  { symbol: 'EMR', name: 'Emerson Electric Co.', sector: 'Industrials', industry: 'Electrical Components' },
  { symbol: 'ETN', name: 'Eaton Corporation plc', sector: 'Industrials', industry: 'Electrical Components' },
  { symbol: 'CARR', name: 'Carrier Global Corporation', sector: 'Industrials', industry: 'Building Products' },
  { symbol: 'OTIS', name: 'Otis Worldwide Corporation', sector: 'Industrials', industry: 'Industrial Machinery' },
  { symbol: 'JCI', name: 'Johnson Controls International plc', sector: 'Industrials', industry: 'Building Products' },
  { symbol: 'TT', name: 'Trane Technologies plc', sector: 'Industrials', industry: 'Building Products' },
  { symbol: 'FDX', name: 'FedEx Corporation', sector: 'Industrials', industry: 'Air Freight & Logistics' },
  { symbol: 'CSX', name: 'CSX Corporation', sector: 'Industrials', industry: 'Railroads' },
  { symbol: 'NSC', name: 'Norfolk Southern Corporation', sector: 'Industrials', industry: 'Railroads' },
  { symbol: 'CHRW', name: 'C.H. Robinson Worldwide Inc.', sector: 'Industrials', industry: 'Air Freight & Logistics' },
  { symbol: 'DAL', name: 'Delta Air Lines Inc.', sector: 'Industrials', industry: 'Airlines' },
  { symbol: 'AAL', name: 'American Airlines Group Inc.', sector: 'Industrials', industry: 'Airlines' },
  { symbol: 'UAL', name: 'United Airlines Holdings Inc.', sector: 'Industrials', industry: 'Airlines' },
  { symbol: 'LUV', name: 'Southwest Airlines Co.', sector: 'Industrials', industry: 'Airlines' },
  { symbol: 'CPRT', name: 'Copart Inc.', sector: 'Industrials', industry: 'Automotive Retail' },
  { symbol: 'WAB', name: 'Wabtec Corporation', sector: 'Industrials', industry: 'Rail Transportation' },
  { symbol: 'DOV', name: 'Dover Corporation', sector: 'Industrials', industry: 'Industrial Machinery' },
  { symbol: 'PH', name: 'Parker-Hannifin Corporation', sector: 'Industrials', industry: 'Industrial Machinery' },
  { symbol: 'ROK', name: 'Rockwell Automation Inc.', sector: 'Industrials', industry: 'Industrial Machinery' },
  { symbol: 'ITW', name: 'Illinois Tool Works Inc.', sector: 'Industrials', industry: 'Industrial Machinery' },
  { symbol: 'IR', name: 'Ingersoll Rand Inc.', sector: 'Industrials', industry: 'Industrial Machinery' },
  { symbol: 'FAST', name: 'Fastenal Company', sector: 'Industrials', industry: 'Building Products' },
  { symbol: 'GWW', name: 'W.W. Grainger Inc.', sector: 'Industrials', industry: 'Industrial Distribution' },
  { symbol: 'AME', name: 'AMETEK Inc.', sector: 'Industrials', industry: 'Electrical Components' },
  { symbol: 'PAYX', name: 'Paychex Inc.', sector: 'Industrials', industry: 'Human Resources & Employment Services' },
  { symbol: 'CTAS', name: 'Cintas Corporation', sector: 'Industrials', industry: 'Human Resources & Employment Services' },
  { symbol: 'RSG', name: 'Republic Services Inc.', sector: 'Industrials', industry: 'Environmental & Facilities Services' },
  { symbol: 'WM', name: 'Waste Management Inc.', sector: 'Industrials', industry: 'Environmental & Facilities Services' },
  { symbol: 'ECL', name: 'Ecolab Inc.', sector: 'Industrials', industry: 'Specialty Chemicals' },
  { symbol: 'DE', name: 'Deere & Company', sector: 'Industrials', industry: 'Agricultural Machinery' },
  { symbol: 'PCAR', name: 'PACCAR Inc.', sector: 'Industrials', industry: 'Construction Machinery' },
  { symbol: 'CMI', name: 'Cummins Inc.', sector: 'Industrials', industry: 'Industrial Machinery' },
  { symbol: 'PWR', name: 'Quanta Services Inc.', sector: 'Industrials', industry: 'Construction & Engineering' },
  { symbol: 'VRSK', name: 'Verisk Analytics Inc.', sector: 'Industrials', industry: 'Research & Consulting Services' },

  // ─── Consumer Staples ───
  { symbol: 'PG', name: 'The Procter & Gamble Company', sector: 'Consumer Staples', industry: 'Household Products' },
  { symbol: 'KO', name: 'The Coca-Cola Company', sector: 'Consumer Staples', industry: 'Soft Drinks' },
  { symbol: 'PEP', name: 'PepsiCo Inc.', sector: 'Consumer Staples', industry: 'Soft Drinks & Non-alcoholic Beverages' },
  { symbol: 'WMT', name: 'Walmart Inc.', sector: 'Consumer Staples', industry: 'Hypermarkets & Super Centers' },
  { symbol: 'COST', name: 'Costco Wholesale Corporation', sector: 'Consumer Staples', industry: 'Hypermarkets & Super Centers' },
  { symbol: 'PM', name: 'Philip Morris International Inc.', sector: 'Consumer Staples', industry: 'Tobacco' },
  { symbol: 'MO', name: 'Altria Group Inc.', sector: 'Consumer Staples', industry: 'Tobacco' },
  { symbol: 'MDLZ', name: 'Mondelez International Inc.', sector: 'Consumer Staples', industry: 'Packaged Foods' },
  { symbol: 'CL', name: 'Colgate-Palmolive Company', sector: 'Consumer Staples', industry: 'Household Products' },
  { symbol: 'KMB', name: 'Kimberly-Clark Corporation', sector: 'Consumer Staples', industry: 'Household Products' },
  { symbol: 'SYY', name: 'Sysco Corporation', sector: 'Consumer Staples', industry: 'Food Distributors' },
  { symbol: 'CAG', name: 'Conagra Brands Inc.', sector: 'Consumer Staples', industry: 'Packaged Foods' },
  { symbol: 'CPB', name: 'Campbell\'s Company', sector: 'Consumer Staples', industry: 'Packaged Foods' },
  { symbol: 'KHC', name: 'The Kraft Heinz Company', sector: 'Consumer Staples', industry: 'Packaged Foods' },
  { symbol: 'GIS', name: 'General Mills Inc.', sector: 'Consumer Staples', industry: 'Packaged Foods' },
  { symbol: 'K', name: 'Kellanova', sector: 'Consumer Staples', industry: 'Packaged Foods' },
  { symbol: 'HRL', name: 'Hormel Foods Corporation', sector: 'Consumer Staples', industry: 'Packaged Foods' },
  { symbol: 'MKC', name: 'McCormick & Company Incorporated', sector: 'Consumer Staples', industry: 'Packaged Foods' },
  { symbol: 'STZ', name: 'Constellation Brands Inc.', sector: 'Consumer Staples', industry: 'Brewers' },
  { symbol: 'TAP', name: 'Molson Coors Beverage Company', sector: 'Consumer Staples', industry: 'Brewers' },
  { symbol: 'CLX', name: 'The Clorox Company', sector: 'Consumer Staples', industry: 'Household Products' },
  { symbol: 'EL', name: 'The Estée Lauder Companies Inc.', sector: 'Consumer Staples', industry: 'Personal Care' },
  { symbol: 'CHD', name: 'Church & Dwight Co. Inc.', sector: 'Consumer Staples', industry: 'Household Products' },
  { symbol: 'KDP', name: 'Keurig Dr Pepper Inc.', sector: 'Consumer Staples', industry: 'Soft Drinks' },
  { symbol: 'MNST', name: 'Monster Beverage Corporation', sector: 'Consumer Staples', industry: 'Soft Drinks' },
  { symbol: 'DLTR', name: 'Dollar Tree Inc.', sector: 'Consumer Staples', industry: 'Discount Stores' },
  { symbol: 'DG', name: 'Dollar General Corporation', sector: 'Consumer Staples', industry: 'Discount Stores' },
  { symbol: 'WBA', name: 'Walgreens Boots Alliance Inc.', sector: 'Consumer Staples', industry: 'Drug Retail' },
  { symbol: 'KR', name: 'The Kroger Co.', sector: 'Consumer Staples', industry: 'Food Retail' },
  { symbol: 'ADM', name: 'Archer-Daniels-Midland Company', sector: 'Consumer Staples', industry: 'Agricultural Products' },
  { symbol: 'TSN', name: 'Tyson Foods Inc.', sector: 'Consumer Staples', industry: 'Packaged Foods' },

  // ─── Energy ───
  { symbol: 'XOM', name: 'Exxon Mobil Corporation', sector: 'Energy', industry: 'Integrated Oil & Gas' },
  { symbol: 'CVX', name: 'Chevron Corporation', sector: 'Energy', industry: 'Integrated Oil & Gas' },
  { symbol: 'COP', name: 'ConocoPhillips', sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  { symbol: 'OXY', name: 'Occidental Petroleum Corporation', sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  { symbol: 'EOG', name: 'EOG Resources Inc.', sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  { symbol: 'PXD', name: 'Pioneer Natural Resources Company', sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  { symbol: 'HES', name: 'Hess Corporation', sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  { symbol: 'DVN', name: 'Devon Energy Corporation', sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  { symbol: 'MPC', name: 'Marathon Petroleum Corporation', sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  { symbol: 'PSX', name: 'Phillips 66', sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  { symbol: 'VLO', name: 'Valero Energy Corporation', sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  { symbol: 'HAL', name: 'Halliburton Company', sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  { symbol: 'SLB', name: 'Schlumberger N.V.', sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  { symbol: 'BKR', name: 'Baker Hughes Company', sector: 'Energy', industry: 'Oil & Gas Equipment & Services' },
  { symbol: 'KMI', name: 'Kinder Morgan Inc.', sector: 'Energy', industry: 'Oil & Gas Storage & Transportation' },
  { symbol: 'WMB', name: 'The Williams Companies Inc.', sector: 'Energy', industry: 'Oil & Gas Storage & Transportation' },
  { symbol: 'OKE', name: 'ONEOK Inc.', sector: 'Energy', industry: 'Oil & Gas Storage & Transportation' },
  { symbol: 'TRGP', name: 'Targa Resources Corp.', sector: 'Energy', industry: 'Oil & Gas Storage & Transportation' },
  { symbol: 'MRO', name: 'Marathon Oil Corporation', sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  { symbol: 'APA', name: 'APA Corporation', sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  { symbol: 'CTRA', name: 'Coterra Energy Inc.', sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  { symbol: 'OVV', name: 'Ovintiv Inc.', sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  { symbol: 'DINO', name: 'HF Sinclair Corporation', sector: 'Energy', industry: 'Oil & Gas Refining & Marketing' },
  { symbol: 'FANG', name: 'Diamondback Energy Inc.', sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  { symbol: 'EQT', name: 'EQT Corporation', sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  { symbol: 'SWN', name: 'Southwestern Energy Company', sector: 'Energy', industry: 'Oil & Gas Exploration & Production' },
  { symbol: 'CNP', name: 'CenterPoint Energy Inc.', sector: 'Energy', industry: 'Multi-Utilities' },

  // ─── Utilities ───
  { symbol: 'NEE', name: 'NextEra Energy Inc.', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'DUK', name: 'Duke Energy Corporation', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'SO', name: 'The Southern Company', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'D', name: 'Dominion Energy Inc.', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'AEP', name: 'American Electric Power Company Inc.', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'EXC', name: 'Exelon Corporation', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'SRE', name: 'Sempra', sector: 'Utilities', industry: 'Multi-Utilities' },
  { symbol: 'XEL', name: 'Xcel Energy Inc.', sector: 'Utilities', industry: 'Multi-Utilities' },
  { symbol: 'PEG', name: 'Public Service Enterprise Group Inc.', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'ED', name: 'Consolidated Edison Inc.', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'EIX', name: 'Edison International', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'AWK', name: 'American Water Works Company Inc.', sector: 'Utilities', industry: 'Water Utilities' },
  { symbol: 'WEC', name: 'WEC Energy Group Inc.', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'ETR', name: 'Entergy Corporation', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'AEE', name: 'Ameren Corporation', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'DTE', name: 'DTE Energy Company', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'FE', name: 'FirstEnergy Corporation', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'PPL', name: 'PPL Corporation', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'ES', name: 'Eversource Energy', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'CMS', name: 'CMS Energy Corporation', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'ATO', name: 'Atmos Energy Corporation', sector: 'Utilities', industry: 'Gas Utilities' },
  { symbol: 'LNT', name: 'Alliant Energy Corporation', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'NI', name: 'NiSource Inc.', sector: 'Utilities', industry: 'Multi-Utilities' },
  { symbol: 'AGR', name: 'Avangrid Inc.', sector: 'Utilities', industry: 'Electric Utilities' },
  { symbol: 'CNP', name: 'CenterPoint Energy Inc.', sector: 'Utilities', industry: 'Multi-Utilities' },
  { symbol: 'NRG', name: 'NRG Energy Inc.', sector: 'Utilities', industry: 'Independent Power Producers' },
  { symbol: 'AES', name: 'The AES Corporation', sector: 'Utilities', industry: 'Independent Power Producers' },
  { symbol: 'CEG', name: 'Constellation Energy Corporation', sector: 'Utilities', industry: 'Independent Power Producers' },
  { symbol: 'VST', name: 'Vistra Corp.', sector: 'Utilities', industry: 'Independent Power Producers' },
  { symbol: 'PCG', name: 'PG&E Corporation', sector: 'Utilities', industry: 'Electric Utilities' },

  // ─── Real Estate ───
  { symbol: 'PLD', name: 'Prologis Inc.', sector: 'Real Estate', industry: 'Industrial REITs' },
  { symbol: 'AMT', name: 'American Tower Corporation', sector: 'Real Estate', industry: 'Telecom Tower REITs' },
  { symbol: 'CCI', name: 'Crown Castle Inc.', sector: 'Real Estate', industry: 'Telecom Tower REITs' },
  { symbol: 'EQIX', name: 'Equinix Inc.', sector: 'Real Estate', industry: 'Data Center REITs' },
  { symbol: 'DLR', name: 'Digital Realty Trust Inc.', sector: 'Real Estate', industry: 'Data Center REITs' },
  { symbol: 'PSA', name: 'Public Storage', sector: 'Real Estate', industry: 'Self-Storage REITs' },
  { symbol: 'O', name: 'Realty Income Corporation', sector: 'Real Estate', industry: 'Retail REITs' },
  { symbol: 'SPG', name: 'Simon Property Group Inc.', sector: 'Real Estate', industry: 'Retail REITs' },
  { symbol: 'WELL', name: 'Welltower Inc.', sector: 'Real Estate', industry: 'Healthcare REITs' },
  { symbol: 'AVB', name: 'AvalonBay Communities Inc.', sector: 'Real Estate', industry: 'Residential REITs' },
  { symbol: 'EQR', name: 'Equity Residential', sector: 'Real Estate', industry: 'Residential REITs' },
  { symbol: 'ESS', name: 'Essex Property Trust Inc.', sector: 'Real Estate', industry: 'Residential REITs' },
  { symbol: 'MAA', name: 'Mid-America Apartment Communities', sector: 'Real Estate', industry: 'Residential REITs' },
  { symbol: 'UDR', name: 'UDR Inc.', sector: 'Real Estate', industry: 'Residential REITs' },
  { symbol: 'INVH', name: 'Invitation Homes Inc.', sector: 'Real Estate', industry: 'Residential REITs' },
  { symbol: 'SUI', name: 'Sun Communities Inc.', sector: 'Real Estate', industry: 'Manufactured Home REITs' },
  { symbol: 'ARE', name: 'Alexandria Real Estate Equities', sector: 'Real Estate', industry: 'Life Science REITs' },
  { symbol: 'CBRE', name: 'CBRE Group Inc.', sector: 'Real Estate', industry: 'Real Estate Services' },
  { symbol: 'IRM', name: 'Iron Mountain Incorporated', sector: 'Real Estate', industry: 'Information Storage REITs' },
  { symbol: 'WY', name: 'Weyerhaeuser Company', sector: 'Real Estate', industry: 'Timber REITs' },
  { symbol: 'BXP', name: 'Boston Properties Inc.', sector: 'Real Estate', industry: 'Office REITs' },
  { symbol: 'HST', name: 'Host Hotels & Resorts Inc.', sector: 'Real Estate', industry: 'Hotel & Resort REITs' },
  { symbol: 'KIM', name: 'Kimco Realty Corporation', sector: 'Real Estate', industry: 'Retail REITs' },
  { symbol: 'REG', name: 'Regency Centers Corporation', sector: 'Real Estate', industry: 'Retail REITs' },
  { symbol: 'FRT', name: 'Federal Realty Investment Trust', sector: 'Real Estate', industry: 'Retail REITs' },

  // ─── Materials ───
  { symbol: 'LIN', name: 'Linde plc', sector: 'Materials', industry: 'Industrial Gases' },
  { symbol: 'APD', name: 'Air Products and Chemicals Inc.', sector: 'Materials', industry: 'Industrial Gases' },
  { symbol: 'ECL', name: 'Ecolab Inc.', sector: 'Materials', industry: 'Specialty Chemicals' },
  { symbol: 'SHW', name: 'The Sherwin-Williams Company', sector: 'Materials', industry: 'Specialty Chemicals' },
  { symbol: 'PPG', name: 'PPG Industries Inc.', sector: 'Materials', industry: 'Specialty Chemicals' },
  { symbol: 'NEM', name: 'Newmont Corporation', sector: 'Materials', industry: 'Gold' },
  { symbol: 'FCX', name: 'Freeport-McMoRan Inc.', sector: 'Materials', industry: 'Copper' },
  { symbol: 'DOW', name: 'Dow Inc.', sector: 'Materials', industry: 'Commodity Chemicals' },
  { symbol: 'DD', name: 'DuPont de Nemours Inc.', sector: 'Materials', industry: 'Specialty Chemicals' },
  { symbol: 'LYB', name: 'LyondellBasell Industries N.V.', sector: 'Materials', industry: 'Commodity Chemicals' },
  { symbol: 'ECL', name: 'Ecolab Inc.', sector: 'Materials', industry: 'Specialty Chemicals' },
  { symbol: 'CTVA', name: 'Corteva Inc.', sector: 'Materials', industry: 'Agricultural Chemicals' },
  { symbol: 'CF', name: 'CF Industries Holdings Inc.', sector: 'Materials', industry: 'Agricultural Chemicals' },
  { symbol: 'MOS', name: 'The Mosaic Company', sector: 'Materials', industry: 'Agricultural Chemicals' },
  { symbol: 'FMC', name: 'FMC Corporation', sector: 'Materials', industry: 'Agricultural Chemicals' },
  { symbol: 'ALB', name: 'Albemarle Corporation', sector: 'Materials', industry: 'Specialty Chemicals' },
  { symbol: 'BLL', name: 'Ball Corporation', sector: 'Materials', industry: 'Metal & Glass Containers' },
  { symbol: 'IP', name: 'International Paper Company', sector: 'Materials', industry: 'Paper & Plastic Packaging' },
  { symbol: 'PKG', name: 'Packaging Corporation of America', sector: 'Materials', industry: 'Paper & Plastic Packaging' },
  { symbol: 'WRK', name: 'WestRock Company', sector: 'Materials', industry: 'Paper & Plastic Packaging' },
  { symbol: 'SEE', name: 'Sealed Air Corporation', sector: 'Materials', industry: 'Paper & Plastic Packaging' },
  { symbol: 'AVY', name: 'Avery Dennison Corporation', sector: 'Materials', industry: 'Paper & Plastic Packaging' },
  { symbol: 'EMN', name: 'Eastman Chemical Company', sector: 'Materials', industry: 'Specialty Chemicals' },
  { symbol: 'CE', name: 'Celanese Corporation', sector: 'Materials', industry: 'Specialty Chemicals' },
  { symbol: 'IFF', name: 'International Flavors & Fragrances', sector: 'Materials', industry: 'Specialty Chemicals' },
  { symbol: 'NUE', name: 'Nucor Corporation', sector: 'Materials', industry: 'Steel' },
  { symbol: 'STLD', name: 'Steel Dynamics Inc.', sector: 'Materials', industry: 'Steel' },
  { symbol: 'RS', name: 'Reliance Steel & Aluminum Co.', sector: 'Materials', industry: 'Steel' },
  { symbol: 'CLF', name: 'Cleveland-Cliffs Inc.', sector: 'Materials', industry: 'Steel' },
  { symbol: 'VMC', name: 'Vulcan Materials Company', sector: 'Materials', industry: 'Construction Materials' },
  { symbol: 'MLM', name: 'Martin Marietta Materials Inc.', sector: 'Materials', industry: 'Construction Materials' },
  { symbol: 'EXP', name: 'Eagle Materials Inc.', sector: 'Materials', industry: 'Construction Materials' },
]

export const SP500_SYMBOLS = SP500_LIST.map(c => c.symbol)

export const SP500_BY_SECTOR = SP500_LIST.reduce<Record<string, SP500Company[]>>((acc, company) => {
  if (!acc[company.sector]) acc[company.sector] = []
  acc[company.sector].push(company)
  return acc
}, {})
